### PR TITLE
Update goodwy.xml

### PR DESCRIPTION
**Pull request by p0k33m0n**
updating polish language strings for Messages

### CODE REVIEW

**Comment by Goodwy** [comment]
I made the corrections manually.
You have translated the file for English. For Polish it is located in .../app/src/main/res/values-pl/ folder.

**Comment by p0k33m0n** [comment]
Thank you, but I was looking there and couldn't find these strings. Should I add them myself next time?

**Comment by Goodwy** [comment]
Yes, I might add. If there are no strings for a particular language, then the strings from the English file are taken.

**Comment by p0k33m0n** [comment]
OK! Thx.

**Pull request closed without merging**
